[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Regular Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Command"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1

[window.dimensions]
columns = 150
lines = 50

[window.padding]
x = 0
y = 0

[general]
import = ["~/.config/alacritty/themes/rose-pine/dist/rose-pine.toml"]
